selenium-hub:
  restart: always
  image: selenium/hub:latest
  ports:
    - "4444:4444"
#selenium-chrome
selenium-chrome:
  restart: always
  image: selenium/node-chrome-debug:latest
  ports:
    - 5900
  links:
    - selenium-hub:hub
#selenium-firefox
selenium-firefox:
  restart: always
  image: selenium/node-firefox-debug:latest
  ports:
    - 5900
  links:
    - selenium-hub:hub